#!/usr/bin/env bash
# Concern 1 of 4: SECRETS (bootstrap). Owns every secret for the environment in
# one CloudFormation stack (deploy/cfn/00-secrets.yaml): the RDS master
# credentials (ltride/db) and the Flask application secret (ltride/app). This
# stack is deployed FIRST — the database stack resolves the DB password from it,
# and the compute stack reads both secrets on the box. See deploy/README.md.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/deploy-common.sh"

database_secret_id="${project_name}/db"
application_secret_id="${project_name}/app"

# Which named values callers may set, and the secret each one lives in. The
# database password/username live in ltride/db; the Flask key lives in ltride/app.
secret_target_for() {
  case "$1" in
    db_username|db_password) printf '%s' "$database_secret_id" ;;
    secret_key)              printf '%s' "$application_secret_id" ;;
    *) return 1 ;;
  esac
}

initialize_secrets() {
  # Create both secrets in one stack. GenerateSecretString fills the DB password
  # and the Flask secret_key with strong random values automatically, so a
  # first-time deploy needs no hand-entered secret.
  deploy_stack secrets 00-secrets.yaml
  echo "secrets stack deployed: ${database_secret_id}, ${application_secret_id}"
}

set_secret_value() {
  # set_secret_value <name> <value> — merge one named value into its secret.
  local name="$1" value="$2" secret_id
  if ! secret_id="$(secret_target_for "$name")"; then
    echo "unknown secret name: ${name}" >&2
    echo "accepted names: db_username, db_password (ltride/db); secret_key (ltride/app)." >&2
    return 2
  fi
  put_secret_key "$secret_id" "$name" "$value"
  echo "set ${name} in ${secret_id}."
  if [ "$name" = "db_password" ]; then
    echo "NOTE: this does not rotate the live RDS password. Update RDS separately if needed." >&2
  fi
}

list_secrets() {
  # Print both secrets' full JSON (name and value). Intended for an operator who
  # already has access; do not paste the output anywhere shared.
  local name
  for name in "$database_secret_id" "$application_secret_id"; do
    printf '%s = %s\n' "$name" "$(get_secret_json "$name")"
  done
}

ensure_required() {
  # Used by the guided 'all' flow: confirm the values the box needs exist. They
  # are auto-generated by 'init', so this is normally just a presence check.
  secret_has_keys "$database_secret_id" username password \
    || { echo "missing username/password in ${database_secret_id}; run 'secrets init'." >&2; return 1; }
  secret_has_keys "$application_secret_id" secret_key \
    || { echo "missing secret_key in ${application_secret_id}; run 'secrets init'." >&2; return 1; }
  echo "required secret values present."
}

destroy_secrets() {
  confirm_destroy "the secrets stack (${database_secret_id}, ${application_secret_id})" || exit 1
  delete_stack secrets
  echo "secrets stack deleted (Secrets Manager schedules the secrets for deletion)."
}

usage() {
  cat <<'USAGE'
Usage: scripts/deploy-secrets.sh <command>   (concern 1 of 4: secrets)

  init            Deploy the secrets stack (auto-generates the DB password + Flask key)
  list            Print both secrets' name and value
  ensure          Verify the required values exist (used by the guided flow)
  <name> <value>  Set/rotate one value: db_username | db_password | secret_key
  destroy         Delete the secrets stack (prompts for confirmation)
USAGE
}

command_name="${1:-list}"
case "$command_name" in
  init)    initialize_secrets ;;
  list)    list_secrets ;;
  ensure)  ensure_required ;;
  destroy) destroy_secrets ;;
  -h|--help|help) usage ;;
  *)
    if [ "$#" -ge 2 ]; then set_secret_value "$command_name" "$2"
    else echo "unknown command: $command_name" >&2; usage; exit 2; fi ;;
esac
